### ISSUE TITLE
uncaught exception: pyOCD.pyDAPAccess.dap_access_api.TransferError

### ISSUE THREAD

**Issue by cederom** [mbedmicro/pyOCD#337]
```
(venv-mac-27) iCeDeROM:cederom cederom$ mbedls
+---------------+----------------------+------------------+------------------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point      | serial_port            | target_id                                        | daplink_version |
+---------------+----------------------+------------------+------------------------+--------------------------------------------------+-----------------+
| LPC812        | LPC812[0]            | /Volumes/DAPLINK | /dev/tty.usbmodem14132 | 10500000e062b0bf00000000000000000000000097969902 | 0243            |
+---------------+----------------------+------------------+------------------------+--------------------------------------------------+-----------------+

(venv-mac-27) iCeDeROM:cederom cederom$ pyocd-gdbserver
0000225:INFO:cmsis_dap_core:DAP SWD MODE initialized
uncaught exception:
Traceback (most recent call last):
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/tools/gdb_server.py", line 299, in run
    frequency=self.args.frequency)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/board/mbed_board.py", line 273, in chooseBoard
    mbed.init()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/board/board.py", line 50, in init
    self.target.init()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/core/coresight_target.py", line 84, in init
    self.dp.init()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 113, in init
    self.read_id_code()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 118, in read_id_code
    self.dpidr = self.read_reg(DP_REG['IDCODE'])
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 134, in read_reg
    return self.readDP(addr, now)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 207, in readDP
    return readDPCb()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 198, in readDPCb
    result = result_cb()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 652, in read_reg_cb
    res = transfer.get_result()
  File "/U(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 119, in get_result
    self.daplink.flush()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 583, in flush
    self._read_packet()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 738, in _read_packet
    decoded_data = cmd.decode_data(raw_data)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 417, in decode_data
    data = self._decode_transfer_block_data(data)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 384, in _decode_transfer_block_data
    raise DAPAccessIntf.TransferError()
TransferError

(venv-mac-27) iCeDeROM:cederom cederom$ pyocd-flashtool
INFO:root:DAP SWD MODE initialized
Traceback (most recent call last):
  File "/(..)/venv-mac-27/bin/pyocd-flashtool", line 11, in <module>
    load_entry_point('pyOCD==0.8.1a2.dev66', 'console_scripts', 'pyocd-flashtool')()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/tools/flash_tool.py", line 153, in main
    frequency=args.frequency, blocking=False)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/board/mbed_board.py", line 273, in chooseBoard
    mbed.init()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/board/board.py", line 50, in init
    self.target.init()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/core/coresight_target.py", line 84, in init
    self.dp.init()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 113, in init
    self.read_id_code()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 118, in read_id_code
    self.dpidr = self.read_reg(DP_REG['IDCODE'])
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 134, in read_reg
    return self.readDP(addr, now)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 207, in readDP
    return readDPCb()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/coresight/dap.py", line 198, in readDPCb
    result = result_cb()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 652, in read_reg_cb
    res = transfer.get_result()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 119, in get_result
    self.daplink.flush()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 583, in flush
    self._read_packet()
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 738, in _read_packet
    decoded_data = cmd.decode_data(raw_data)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 417, in decode_data
    data = self._decode_transfer_block_data(data)
  File "/(..)/venv-mac-27/lib/python2.7/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 384, in _decode_transfer_block_data
    raise DAPAccessIntf.TransferError()
pyOCD.pyDAPAccess.dap_access_api.TransferError

(venv-mac-27) iCeDeROM:cederom cederom$ pyocd-flashtool --version
0.8.1a2.dev66

(venv-mac-27) iCeDeROM:cederom cederom$ pip install -r DAPLink.git/requirements.txt
Requirement already satisfied: project_generator<0.10.0,>=0.9.8 in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 1))
Requirement already satisfied: mbed_ls in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 2))
Requirement already satisfied: pyserial in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 3))
Requirement already satisfied: pyOCD>=0.7.0 in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 4))
Requirement already satisfied: requests in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 5))
Requirement already satisfied: intelhex in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 6))
Requirement already satisfied: six in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 7))
Requirement already satisfied: enum34 in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 8))
Requirement already satisfied: pyusb in ./venv-mac-27/lib/python2.7/site-packages (from -r DAPLink.git/requirements.txt (line 9))
Requirement already satisfied: argparse in ./venv-mac-27/lib/python2.7/site-packages (from project_generator<0.10.0,>=0.9.8->-r DAPLink.git/requirements.txt (line 1))
Requirement already satisfied: project-generator-definitions<0.3.0,>=0.2.2 in ./venv-mac-27/lib/python2.7/site-packages (from project_generator<0.10.0,>=0.9.8->-r DAPLink.git/requirements.txt (line 1))
Requirement already satisfied: xmltodict in ./venv-mac-27/lib/python2.7/site-packages (from project_generator<0.10.0,>=0.9.8->-r DAPLink.git/requirements.txt (line 1))
Requirement already satisfied: Jinja2 in ./venv-mac-27/lib/python2.7/site-packages (from project_generator<0.10.0,>=0.9.8->-r DAPLink.git/requirements.txt (line 1))
Requirement already satisfied: pyYAML in ./venv-mac-27/lib/python2.7/site-packages (from project_generator<0.10.0,>=0.9.8->-r DAPLink.git/requirements.txt (line 1))
Requirement already satisfied: fasteners in ./venv-mac-27/lib/python2.7/site-packages (from mbed_ls->-r DAPLink.git/requirements.txt (line 2))
Requirement already satisfied: PrettyTable>=0.7.2 in ./venv-mac-27/lib/python2.7/site-packages (from mbed_ls->-r DAPLink.git/requirements.txt (line 2))
Requirement already satisfied: future in ./venv-mac-27/lib/python2.7/site-packages (from pyOCD>=0.7.0->-r DAPLink.git/requirements.txt (line 4))
Requirement already satisfied: websocket-client in ./venv-mac-27/lib/python2.7/site-packages (from pyOCD>=0.7.0->-r DAPLink.git/requirements.txt (line 4))
Requirement already satisfied: hidapi in ./venv-mac-27/lib/python2.7/site-packages (from pyOCD>=0.7.0->-r DAPLink.git/requirements.txt (line 4))
Requirement already satisfied: idna<2.6,>=2.5 in ./venv-mac-27/lib/python2.7/site-packages (from requests->-r DAPLink.git/requirements.txt (line 5))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./venv-mac-27/lib/python2.7/site-packages (from requests->-r DAPLink.git/requirements.txt (line 5))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv-mac-27/lib/python2.7/site-packages (from requests->-r DAPLink.git/requirements.txt (line 5))
Requirement already satisfied: certifi>=2017.4.17 in ./venv-mac-27/lib/python2.7/site-packages (from requests->-r DAPLink.git/requirements.txt (line 5))
Requirement already satisfied: MarkupSafe>=0.23 in ./venv-mac-27/lib/python2.7/site-packages (from Jinja2->project_generator<0.10.0,>=0.9.8->-r DAPLink.git/requirements.txt (line 1))
Requirement already satisfied: monotonic>=0.1 in ./venv-mac-27/lib/python2.7/site-packages (from fasteners->mbed_ls->-r DAPLink.git/requirements.txt (line 2))
Requirement already satisfied: setuptools>=19.0 in ./venv-mac-27/lib/python2.7/site-packages (from hidapi->pyOCD>=0.7.0->-r DAPLink.git/requirements.txt (line 4))
```

**Comment by flit** [comment]
Based on the exception, this is almost certainly a hardware issue. pyOCD isn't even able to read the DP's IDCODE register, which is always accessible as long as the SW-DP or SWJ-DP is powered and pins are connected. As such, I'm going to close this issue. If you have further evidence that this isn't a hardware issue, please feel free to reopen it.
