### ISSUE TITLE
Trying to communicate with the FRDM-K64F using pyOCD

### ISSUE THREAD

**Issue by hellgheast** [mbedmicro/pyOCD#346]
Here's the error i got when trying to communicate with the FRDM-K64F using pyocd.

The firmware and the bootloader are the latest available on : https://www.nxp.com/support/developer-resources/run-time-software/kinetis-developer-resources/ides-for-kinetis-mcus/opensda-serial-and-debug-adapter:OPENSDA?&tid=vanOpenSDA#FRDM-K64F

And here's the DETAIL.txt content of my FRDM-K64F
HIC ID: 97969900
Auto Reset: 0
Automation allowed: 0
Overflow detection: 0
Daplink Mode: Interface
Interface Version: 0244
Bootloader Version: 0244
Git SHA: 392f85aa88a41125dec0b963ce73c6795b8bdd0d
Local Mods: 0
USB Interfaces: MSD, CDC, HID
Bootloader CRC: 0xc4ebf65c
Interface CRC: 0xc525d856
Remount count: 0

I'm on Fedora 26 and i followed all the step of installation of the Zephyr Open Source Project.

[root@localhost bin]# pyocd-gdbserver 
INFO:root:DAP SWD MODE initialised
INFO:root:K64F not in secure state
uncaught exception: 
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/pyOCD/tools/gdb_server.py", line 263, in run
    frequency=self.args.frequency)
  File "/root/.local/lib/python3.6/site-packages/pyOCD/board/mbed_board.py", line 272, in chooseBoard
    mbed.init()
  File "/root/.local/lib/python3.6/site-packages/pyOCD/board/board.py", line 51, in init
    self.target.init()
  File "/root/.local/lib/python3.6/site-packages/pyOCD/target/target_kinetis.py", line 123, in init
    self.aps[0].init(bus_accessible=True)
  File "/root/.local/lib/python3.6/site-packages/pyOCD/coresight/ap.py", line 111, in init
    super(MEM_AP, self).init(bus_accessible)
  File "/root/.local/lib/python3.6/site-packages/pyOCD/coresight/ap.py", line 87, in init
    self.init_rom_table()
  File "/root/.local/lib/python3.6/site-packages/pyOCD/coresight/ap.py", line 92, in init_rom_table
    self.rom_table.init()
  File "/root/.local/lib/python3.6/site-packages/pyOCD/coresight/rom_table.py", line 178, in init
    self.read_id_registers()
  File "/root/.local/lib/python3.6/site-packages/pyOCD/coresight/rom_table.py", line 116, in read_id_registers
    regs = self.ap.readBlockMemoryAligned32(self.top_address + PIDR4, IDR_COUNT)
  File "/root/.local/lib/python3.6/site-packages/pyOCD/coresight/ap.py", line 344, in readBlockMemoryAligned32
    resp += self._readBlock32(addr, n/4)
  File "/root/.local/lib/python3.6/site-packages/pyOCD/coresight/ap.py", line 205, in _readBlock32
    resp = self.link.reg_read_repeat(size, reg)
  File "/root/.local/lib/python3.6/site-packages/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 591, in reg_read_repeat
    assert isinstance(num_repeats, six.integer_types)
AssertionError

Has anyone got any similar problem ?

**Comment by hellgheast** [comment]
Got fixed by using openOCD instead of pyOCD

**Comment by flit** [comment]
@hellgheast Fyi, the problem is that you were using Python 3.6. pyOCD does not yet support Python 3, so please use the latest Python 2.7 (2.7.15 at the time of this writing).
