### ISSUE TITLE
Unable to open device

### ISSUE THREAD

**Issue by david9991** [mbedmicro/pyOCD#371]
**OS:** MacOS High Sierra
**pyOCD Version:** master

I have switch my pyOCD to master branch, and cannot connect to the device anymore.
Here is the error message:
```
uncaught exception: Unable to open device
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pyOCD-0.10.1.dev27+dirty-py2.7.egg/pyOCD/tools/gdb_server.py", line 302, in run
    frequency=self.args.frequency)
  File "/Library/Python/2.7/site-packages/pyOCD-0.10.1.dev27+dirty-py2.7.egg/pyOCD/board/mbed_board.py", line 209, in chooseBoard
    mbed.link.open()
  File "/Library/Python/2.7/site-packages/pyOCD-0.10.1.dev27+dirty-py2.7.egg/pyOCD/pyDAPAccess/dap_access_cmsis_dap.py", line 513, in open
    self._interface.open()
  File "/Library/Python/2.7/site-packages/pyOCD-0.10.1.dev27+dirty-py2.7.egg/pyOCD/pyDAPAccess/interface/hidapi_backend.py", line 53, in open
    raise DAPAccessIntf.DeviceError("Unable to open device")
DeviceError: Unable to open device
```
And I also tried to print `deviceInfo` out, but deviceInfo['path'] always empty, that's why "Unable to open device" error occurred.
```
{'usage_page': 65280, 'interface_number': -1, 'product_id': 516, 'serial_number': u'0227000041114e450030300dc403004c5ab1000097969900', 'usage': 1, 'path': '', 'manufacturer_string': u'ARM', 'vendor_id': 3368, 'product_string': u'DAPLink CMSIS-DAP', 'release_number': 4096}
```
How can I get it work again?

**Comment by david9991** [comment]
It's a mistake, native python doesn't work but brew installed python does. So it can be closed.
