### ISSUE TITLE
pyOCD dies when hidapi product name is bytes

### ISSUE THREAD

**Issue by Cypress-OpenOCD** [mbedmicro/pyOCD#527]
Issue was caught on MacOS X. USB 'product_name' returned by hid.enumerate() may contain binary data. Because of this product_name.find("CMSIS-DAP") in hidapi_backend.py fails with the following error:

> pyocd list
0000350:ERROR:__main__:uncaught exception: argument should be integer or bytes-like object, not 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyocd/__main__.py", line 309, in run
    self._commands[self._args.cmd]()
  File "/usr/local/lib/python3.7/site-packages/pyocd/__main__.py", line 336, in do_list
    ConnectHelper.list_connected_probes()
  File "/usr/local/lib/python3.7/site-packages/pyocd/core/helpers.py", line 100, in list_connected_probes
    allProbes = ConnectHelper.get_all_connected_probes(blocking=False)
  File "/usr/local/lib/python3.7/site-packages/pyocd/core/helpers.py", line 78, in get_all_connected_probes
    allProbes = DebugProbeAggregator.get_all_connected_probes(unique_id=unique_id)
  File "/usr/local/lib/python3.7/site-packages/pyocd/probe/aggregator.py", line 32, in get_all_connected_probes
    probes += cls.get_all_connected_probes()
  File "/usr/local/lib/python3.7/site-packages/pyocd/probe/cmsis_dap_probe.py", line 70, in get_all_connected_probes
    return [cls(dev) for dev in DAPAccess.get_connected_devices()]
  File "/usr/local/lib/python3.7/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 438, in get_connected_devices
    all_interfaces = _get_interfaces()
  File "/usr/local/lib/python3.7/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 47, in _get_interfaces
    return INTERFACE[USB_BACKEND].get_all_connected_interfaces()
  File "/usr/local/lib/python3.7/site-packages/pyocd/probe/pydapaccess/interface/hidapi_backend.py", line 76, in get_all_connected_interfaces
    if (product_name.find("CMSIS-DAP") < 0):
TypeError: argument should be integer or bytes-like object, not 'str'

Converting product_name to string resolves the issue:

        for deviceInfo in devices:
            product_name = **str**(deviceInfo['product_string'])
            if (product_name.find("CMSIS-DAP") < 0):
                # Skip non cmsis-dap devices
                continue

Associated pull request #526

**Comment by flit** [comment]
Is this with your DAPLink build or KitProg3? What Python version? Just curious because I've not seen this before.
