### ISSUE TITLE
0.19.0 FreeBSD gdb server usb dev.kernel_detach_driver(interface_number)

### ISSUE THREAD

**Issue by cederom** [mbedmicro/pyOCD#675]
Hello world :-) I have noticed a problem with kernel detach on usb when starting the gdbserver as standard user, it works when running as root, all permissions for user are granted to access the usb devices except kernel operations, will have to find if that detach is really necessary to operate..

```
(venv36bsd) [cd@0xCFC2 ~/cederom/usr/local/venv36bsd/bin]$ pyocd gdb
0000736:INFO:board:Target type is nrf52
0000749:ERROR:__main__:uncaught exception: [Errno None] Other error
Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/__main__.py", line 300, in run
    self._commands[self._args.cmd]()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/__main__.py", line 460, in do_gdbserver
    **sessionOptions)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/helpers.py", line 199, in session_with_chosen_probe
    session.open()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/session.py", line 278, in open
    self._probe.open()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 137, in open
    self._link.open()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 562, in open
    self._interface.open()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/interface/pyusb_backend.py", line 104, in open
    dev.detach_kernel_driver(interface_number)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/usb/core.py", line 1077, in detach_kernel_driver
    interface)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/usb/backend/libusb1.py", line 902, in detach_kernel_driver
    _check(self.lib.libusb_detach_kernel_driver(dev_handle.handle, intf))
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno None] Other error

(venv36bsd) [cd@0xCFC2 ~/cederom/usr/local/venv36bsd/bin]$ pyocd -V
0.19.0

(venv36bsd) [cd@0xCFC2 ~/cederom/usr/local/venv36bsd/bin]$ uname -a
FreeBSD 0xCFC2 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64
```

**Comment by cederom** [comment]
The problem is:
* with `pyocd/probe/pydapaccess/interface/pyusb_backend.py`, line `104`, in `dev.detach_kernel_driver(interface_number)`. Simply commenting out this line allows me to debug with no problem as user. Is there any other reason we want to detach any interface here?
* two lines later exception is supposed to catch `NotImplementedError`, but does not catch `usb.core.USBError: [Errno None] Other error`. Should we catch all exceptions here? Maybe except `Errno None`?

Any hints welcome @flit  :-)

**Comment by cederom** [comment]
Got back to this problem even with simple `pyocd reset` after update. Will look into it and propose a solution :-)

**Comment by cederom** [comment]
Allright, the pyOCD tries to unload kernel driver for interface 3 on DAPLink, that is HID CMSIS-DAP. We do not really want to detach HID driver for the whole system and normal user is not permitted to. Nothing happens if we skip that unload, DAPLink works fine.. also nothing was handled in the exception handler anyway.. so I have changed source to simply catch all exceptions and print some debug and warning messages that may come useful :-)

https://github.com/mbedmicro/pyOCD/pull/939

**Comment by cederom** [comment]
The only minor issue left is that exception raises `[None] Other error` code / message. FreeBSD has its own LibUSB implementation. It looks like the error codes may differ between implementations. Someone reported similar problem with LimeSDR device. I will look into it in a free moment.. but the blocker seems to be fixed :-)

**Comment by cederom** [comment]
Patch committed to the master. Closing. Thank you @flit :-)
