### ISSUE TITLE
0.19.0 FreeBSD dap probe uncaught exception

### ISSUE THREAD

**Issue by cederom** [mbedmicro/pyOCD#676]
I found that when running `pyocd gdb`.. maybe fixed in following releases?

```
(venv36bsd) pyocd gdb
0000969:INFO:board:Target type is nrf52
0001008:ERROR:__main__:uncaught exception:
Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 260, in read_dp_result_callback
    return result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 791, in read_reg_cb
    res = transfer.get_result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 137, in get_result
    self.daplink.flush()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 650, in flush
    self._read_packet()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 877, in _read_packet
    decoded_data = cmd.decode_data(raw_data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 435, in decode_data
    data = self._decode_transfer_block_data(data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 402, in _decode_transfer_block_data
    raise DAPAccessIntf.TransferError()
pyocd.probe.pydapaccess.dap_access_api.DAPAccessIntf.TransferError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 101, in init
    self.read_id_code()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 111, in read_id_code
    self.dpidr = self.read_reg(DP_IDCODE)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 125, in read_reg
    return self.read_dp(addr, now)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 243, in read_dp
    return read_dp_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 234, in read_dp_cb
    result = result_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 263, in read_dp_result_callback
    six.raise_from(self._convert_exception(error), error)
  File "<string>", line 3, in raise_from
pyocd.core.exceptions.TransferError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 260, in read_dp_result_callback
    return result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 791, in read_reg_cb
    res = transfer.get_result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 137, in get_result
    self.daplink.flush()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 650, in flush
    self._read_packet()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 877, in _read_packet
    decoded_data = cmd.decode_data(raw_data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 435, in decode_data
    data = self._decode_transfer_block_data(data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 402, in _decode_transfer_block_data
    raise DAPAccessIntf.TransferError()
pyocd.probe.pydapaccess.dap_access_api.DAPAccessIntf.TransferError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/__main__.py", line 300, in run
    self._commands[self._args.cmd]()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/__main__.py", line 460, in do_gdbserver
    **sessionOptions)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/helpers.py", line 199, in session_with_chosen_probe
    session.open()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/session.py", line 281, in open
    self._board.init()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/board/board.py", line 66, in init
    self.target.init()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/coresight_target.py", line 152, in init
    seq.invoke()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/utility/sequencer.py", line 189, in invoke
    resultSequence = call()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 106, in init
    self.read_id_code()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 111, in read_id_code
    self.dpidr = self.read_reg(DP_IDCODE)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 125, in read_reg
    return self.read_dp(addr, now)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 243, in read_dp
    return read_dp_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 234, in read_dp_cb
    result = result_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 263, in read_dp_result_callback
    six.raise_from(self._convert_exception(error), error)
  File "<string>", line 3, in raise_from
pyocd.core.exceptions.TransferError
(venv36bsd)
(venv36bsd) pyocd gdb
0000486:INFO:board:Target type is nrf52
0000523:ERROR:__main__:uncaught exception:
Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 260, in read_dp_result_callback
    return result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 791, in read_reg_cb
    res = transfer.get_result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 137, in get_result
    self.daplink.flush()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 650, in flush
    self._read_packet()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 877, in _read_packet
    decoded_data = cmd.decode_data(raw_data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 435, in decode_data
    data = self._decode_transfer_block_data(data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 402, in _decode_transfer_block_data
    raise DAPAccessIntf.TransferError()
pyocd.probe.pydapaccess.dap_access_api.DAPAccessIntf.TransferError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 101, in init
    self.read_id_code()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 111, in read_id_code
    self.dpidr = self.read_reg(DP_IDCODE)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 125, in read_reg
    return self.read_dp(addr, now)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 243, in read_dp
    return read_dp_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 234, in read_dp_cb
    result = result_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 263, in read_dp_result_callback
    six.raise_from(self._convert_exception(error), error)
  File "<string>", line 3, in raise_from
pyocd.core.exceptions.TransferError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 260, in read_dp_result_callback
    return result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 791, in read_reg_cb
    res = transfer.get_result()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 137, in get_result
    self.daplink.flush()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 650, in flush
    self._read_packet()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 877, in _read_packet
    decoded_data = cmd.decode_data(raw_data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 435, in decode_data
    data = self._decode_transfer_block_data(data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 402, in _decode_transfer_block_data
    raise DAPAccessIntf.TransferError()
pyocd.probe.pydapaccess.dap_access_api.DAPAccessIntf.TransferError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/__main__.py", line 300, in run
    self._commands[self._args.cmd]()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/__main__.py", line 460, in do_gdbserver
    **sessionOptions)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/helpers.py", line 199, in session_with_chosen_probe
    session.open()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/session.py", line 281, in open
    self._board.init()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/board/board.py", line 66, in init
    self.target.init()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/core/coresight_target.py", line 152, in init
    seq.invoke()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/utility/sequencer.py", line 189, in invoke
    resultSequence = call()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 106, in init
    self.read_id_code()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 111, in read_id_code
    self.dpidr = self.read_reg(DP_IDCODE)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 125, in read_reg
    return self.read_dp(addr, now)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 243, in read_dp
    return read_dp_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/coresight/dap.py", line 234, in read_dp_cb
    result = result_cb()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 263, in read_dp_result_callback
    six.raise_from(self._convert_exception(error), error)
  File "<string>", line 3, in raise_from
pyocd.core.exceptions.TransferError

(venv36bsd) pyocd list
## => Board Name | Unique ID
-- -- ----------------------
 0 => nRF52-DK [nrf52] | 11013602442031204a353043323031323031303897969903

(venv36bsd) pyocd -V
u0.19.0

(venv36bsd) whoami
root

(venv36bsd) uname -a
FreeBSD 0xCFC2 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64
```

**Comment by cederom** [comment]
With experimental build of CPM on FreeBSD [https://github.com/ARMmbed/cmsis-pack-manager/issues/97] I have managed to build pyOCD version `0.21.0` that seems to have this issue fixed. Thank you @flit and @theotherjimmy YOU ROX! =)
