### ISSUE TITLE
0.19.0 FreeBSD gdb load assertion error

### ISSUE THREAD

**Issue by cederom** [mbedmicro/pyOCD#677]
Hello world :-) When connected to a Target, then using `load` in `gdb` AssertionError occurs. That prevents firmware load and debug..

```
(venv36bsd) pyocd gdb
0000494:INFO:board:Target type is nrf52
0000524:INFO:dap:DP IDR = 0x2ba01477
0000536:INFO:dap:AP#0 IDR = 0x24770011
0000539:INFO:dap:AP#1 IDR = 0x02880000
0000545:INFO:rom_table:AP#0 ROM table #0 @ 0xe00ff000 (designer=244 part=006)
0000550:INFO:rom_table:[0]<e000e000:SCS-M4 class=14 designer=43b part=00c>
0000553:INFO:rom_table:[1]<e0001000:DWT class=14 designer=43b part=002>
0000556:INFO:rom_table:[2]<e0002000:FPB class=14 designer=43b part=003>
0000559:INFO:rom_table:[3]<e0000000:ITM class=14 designer=43b part=001>
0000561:INFO:rom_table:[4]<e0040000:TPIU-M4 class=9 designer=43b part=9a1 devtype=11 archid=0000 devid=0:0:ca1>
0000564:INFO:rom_table:[5]<e0041000:ETM-M4 class=9 designer=43b part=925 devtype=13 archid=0000 devid=0:0:0>
0000567:INFO:cortex_m:CPU core #0 is Cortex-M4 r0p1
0000572:INFO:cortex_m:FPU present: FPv4-SP
0000576:INFO:dwt:4 hardware watchpoints
0000578:INFO:fpb:6 hardware breakpoints, 4 literal comparators
0000591:INFO:server:Semihost server started on port 4444
0000592:INFO:gdbserver:GDB server started on port 3333
0031729:INFO:gdbserver:One client connected!
[                    ]   0%0036816:ERROR:gdbserver:Unhandled exception in handle_message:
Traceback (most recent call last):
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/gdbserver/gdbserver.py", line 538, in handle_message
    reply = handler(msg[msgStart:])
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/gdbserver/gdbserver.py", line 759, in v_command
    return self.flash_op(data)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/gdbserver/gdbserver.py", line 870, in flash_op
    self.flash_loader.commit()
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/flash/loader.py", line 505, in commit
    keep_unwritten=self._keep_unwritten)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/flash/flash_builder.py", line 433, in program
    flash_operation = self._sector_erase_program_double_buffer(progress_cb)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/flash/flash_builder.py", line 817, in _sector_erase_program_double_buffer
    progress = self._scan_pages_for_same(progress_cb)
  File "/home/cd/cederom/usr/local/venv36bsd/lib/python3.6/site-packages/pyocd/flash/flash_builder.py", line 777, in _scan_pages_for_same
    assert len(page.data) == page.size
AssertionError

(venv36bsd) pyocd -V
0.19.0

(venv36bsd) uname -a
FreeBSD 0xCFC2 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64
```

**Comment by cederom** [comment]
With experimental build of CPM on FreeBSD [https://github.com/ARMmbed/cmsis-pack-manager/issues/97] I have managed to build pyOCD version `0.21.0` that seems to have this issue fixed. Thank you @flit and @theotherjimmy YOU ROX! =)
