### ISSUE TITLE
TargetSupportError: Target type 'mimxrt0164cvl5a' not recognized.

### ISSUE THREAD

**Issue by Hoohaha** [mbedmicro/pyOCD#678]
I am trying to use pyocd with DFP packs for NXP-EVKMIMXRT1064, but i got an exception

```C:\Dpc\stationscript>pyocd gdbserver --pack "C:\Users\public.DESKTOP-EKGOQNF\Downloads\NXP.MIMXRT1064_DFP.10.0.0.pack"
0000282:WARNING:common:STLink and CMSIS-DAPv2 probes are not supported because no libusb library was found.
## => Board Name | Unique ID
-- -- ----------------------
 0 => MIMXRT1064-EVK [mimxrt0164cvl5a] | 0232000005d851a200000000000000000000000097969905
 1 => MIMXRT1064-EVK [mimxrt0164cvl5a] | 0232000005d8669800000000000000000000000097969905
 2 => MIMXRT1064-EVK [mimxrt0164cvl5a] | 0232000005d8860600000000000000000000000097969905
 3 => MIMXRT1064-EVK [mimxrt0164cvl5a] | 0232000005d9791100000000000000000000000097969905
 q => Quit

Enter the number of the debug probe to connect:
> 0
0002671:CRITICAL:__main__:Target type 'mimxrt0164cvl5a' not recognized. Use 'pyocd list --targets' to see currently available target types. See <https://github.com/mbedmicro/pyOCD/blob/master/docs/target_support.md> for how to install additional target support.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pyocd\__main__.py", line 338, in run
    self._COMMANDS[self._args.cmd](self)
  File "c:\python27\lib\site-packages\pyocd\__main__.py", line 562, in do_gdbserver
    options=sessionOptions)
  File "c:\python27\lib\site-packages\pyocd\core\helpers.py", line 234, in session_with_chosen_probe
    return Session(probe, auto_open=auto_open, options=options, **kwargs)
  File "c:\python27\lib\site-packages\pyocd\core\session.py", line 170, in __init__
    self._board = probe.create_associated_board(self) \
  File "c:\python27\lib\site-packages\pyocd\probe\cmsis_dap_probe.py", line 135, in create_associated_board
    return MbedBoard(session, board_id=self.unique_id[0:4])
  File "c:\python27\lib\site-packages\pyocd\board\mbed_board.py", line 67, in __init__
    super(MbedBoard, self).__init__(session, target)
  File "c:\python27\lib\site-packages\pyocd\board\board.py", line 58, in __init__
    "for how to install additional target support." % self._target_type), exc)
  File "c:\python27\lib\site-packages\six.py", line 737, in raise_from
    raise value
```
DFP .pdsc definitions as, looks like target name is case sensitive, i changed the target name to upper in pyocd.board.board_ids, the issue is gone.

```
  <devices>
    <family Dfamily="MIMXRT1064" Dvendor="NXP:11">
      <description>The MIMXRT1064 are ARM Cortex-M7 based microcontrollers for embedded applications.</description>
      <device Dname="MIMXRT1064xxxxA">
        <processor Dcore="Cortex-M7" Dfpu="DP_FPU" Dendian="Little-endian" Dclock="600000000"/>
        <environment name="iar">
          <file category="linkerfile" name="iar/MIMXRT1064xxxxx_ram.icf"/>
        </environment>
        <memory name="PROGRAM_FLASH" access="rx" start="0x70000000" size="0x400000" startup="1" default="1"/>
        <memory name="SRAM_DTC" access="rw" start="0x20000000" size="0x020000"/>
        <memory name="SRAM_ITC" access="rw" start="0x00000000" size="0x020000"/>
        <memory name="SRAM_OC" access="rw" start="0x20200000" size="0x0c0000" default="1"/>
        <algorithm name="arm/MIMXRT1064_QSPI_4KB_SEC.FLM" start="0x70000000" size="0x400000" default="1"/>
        <debug svd="MIMXRT1064.xml"/>
        <variant Dvariant="MIMXRT1064CVL5A">
          <compile header="fsl_device_registers.h" define="CPU_MIMXRT1064CVL5A"/>
          <environment name="uv">
            <CMisc>--C99</CMisc>
            <LMisc>--scatter "./RTE/Device/MIMXRT1064CVL5A/MIMXRT1064xxxxx_ram.scf"</LMisc>
          </environment>
        </variant>
        <variant Dvariant="MIMXRT1064DVL6A">
          <compile header="fsl_device_registers.h" define="CPU_MIMXRT1064DVL6A"/>
          <environment name="uv">
            <CMisc>--C99</CMisc>
            <LMisc>--scatter "./RTE/Device/MIMXRT1064DVL6A/MIMXRT1064xxxxx_ram.scf"</LMisc>
          </environment>
        </variant>
      </device>
    </family>
  </devices>
```

**Comment by flit** [comment]
Hi @Hoohaha! That's strange that it worked when you made the target type uppercase. I also tried running `pyocd pack --find` with the part number in both lower and upper case, and confirmed this behaviour. However, pyOCD is supposed to make all target type comparison case-insensitive. There must be a comparison somewhere that doesn't do this correctly. Thanks for reporting!
