### ISSUE TITLE
'info registers' call failed

### ISSUE THREAD

**Issue by andrewc-arm** [mbedmicro/pyOCD#689]
## Problem
I tried K64F pyocd debugging and typed in `info registers` to read registers but it failed from pyocd.
This is the gdb console output
```
(gdb) bt
#0  0x0000194a in func2 () at .\main.cpp:18
#1  0x00001960 in func1 () at .\main.cpp:23
#2  0x000019aa in main () at .\main.cpp:38
(gdb) info registers
Remote failure reply: E01
```

This is the pyocd exception output.
```
0013500:INFO:gdbserver:RTX5 loaded successfully
0989993:ERROR:gdbserver:Unhandled exception in handle_message: read error
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pyocd\gdbserver\gdbserver.py", line 537, in handle_message
    reply = handler()
  File "c:\python27\lib\site-packages\pyocd\gdbserver\gdbserver.py", line 972, in get_registers
    return self.create_rsp_packet(self.target_facade.get_register_context())
  File "c:\python27\lib\site-packages\pyocd\gdbserver\context_facade.py", line 67, in get_register_context
    vals = self._context.read_core_registers_raw(reg_num_list)
  File "c:\python27\lib\site-packages\pyocd\debug\cache.py", line 525, in read_core_registers_raw
    return self._regcache.read_core_registers_raw(reg_list)
  File "c:\python27\lib\site-packages\pyocd\debug\cache.py", line 128, in read_core_registers_raw
    self._check_cache()
  File "c:\python27\lib\site-packages\pyocd\debug\cache.py", line 105, in _check_cache
    if self._context.core.is_running():
  File "c:\python27\lib\site-packages\pyocd\coresight\cortex_m.py", line 937, in is_running
    return self.get_state() == Target.TARGET_RUNNING
  File "c:\python27\lib\site-packages\pyocd\coresight\cortex_m.py", line 914, in get_state
    dhcsr = self.read_memory(CortexM.DHCSR)
  File "c:\python27\lib\site-packages\pyocd\coresight\cortex_m.py", line 604, in read_memory
    result = self.ap.read_memory(addr, transfer_size, now)
  File "c:\python27\lib\site-packages\pyocd\coresight\ap.py", line 311, in _read_memory
    result = read_mem_cb()
  File "c:\python27\lib\site-packages\pyocd\coresight\ap.py", line 292, in read_mem_cb
    res = result_cb()
  File "c:\python27\lib\site-packages\pyocd\coresight\dap.py", line 283, in read_ap_cb
    result = result_cb()
  File "c:\python27\lib\site-packages\pyocd\probe\cmsis_dap_probe.py", line 299, in read_ap_result_callback
    return result()
  File "c:\python27\lib\site-packages\pyocd\probe\pydapaccess\dap_access_cmsis_dap.py", line 784, in read_reg_cb
    res = transfer.get_result()
  File "c:\python27\lib\site-packages\pyocd\probe\pydapaccess\dap_access_cmsis_dap.py", line 130, in get_result
    self.daplink.flush()
  File "c:\python27\lib\site-packages\pyocd\probe\pydapaccess\dap_access_cmsis_dap.py", line 643, in flush
    self._read_packet()
  File "c:\python27\lib\site-packages\pyocd\probe\pydapaccess\dap_access_cmsis_dap.py", line 868, in _read_packet
    raw_data = self._interface.read()
  File "c:\python27\lib\site-packages\pyocd\probe\pydapaccess\interface\hidapi_backend.py", line 114, in read
    return self.device.read(self.packet_size)
  File "hid.pyx", line 122, in hid.device.read
IOError: read error
```

## How to reproduce this problem
* Run K64F debugging via `pyocd gdbserver`
* From the GDB client, type in `info registers` and it will fail.

**Comment by andrewc-arm** [comment]
Sorry for the inconvenience. It works. My device was disconnected. 😬
