### ISSUE TITLE
Session initialization fails intermittently for StLink boards

### ISSUE THREAD

**Issue by juhhov** [mbedmicro/pyOCD#695]
Session initialization intermittently fails when StlinkDetectBase fails to acquire target_id_mbed_htm for device. This happens at least with NUCLEO_L073RZ, NUCLEO_F429ZI and NUCLEO_F411RE.

Traceback:
```
Traceback (most recent call last):
File ".../lib/python3.5/site-packages/pyocd/core/helpers.py", line 232, in session_with_chosen_probe
unique_id=unique_id,
File ".../lib/python3.5/site-packages/pyocd/core/helpers.py", line 132, in choose_probe
allProbes = ConnectHelper.get_all_connected_probes(blocking=blocking, unique_id=unique_id)
File ".../lib/python3.5/site-packages/pyocd/core/helpers.py", line 81, in get_all_connected_probes
allProbes = DebugProbeAggregator.get_all_connected_probes(unique_id=unique_id)
File ".../lib/python3.5/site-packages/pyocd/probe/aggregator.py", line 32, in get_all_connected_probes
probes += cls.get_all_connected_probes()
File ".../lib/python3.5/site-packages/pyocd/probe/stlink_probe.py", line 34, in get_all_connected_probes
return [cls(dev) for dev in STLinkUSBInterface.get_all_connected_devices()]
File ".../lib/python3.5/site-packages/pyocd/probe/stlink_probe.py", line 34, in <listcomp>
return [cls(dev) for dev in STLinkUSBInterface.get_all_connected_devices()]
File ".../lib/python3.5/site-packages/pyocd/probe/stlink_probe.py", line 58, in __init__
self._board_id = info['target_id_mbed_htm'][0:4]
KeyError: 'target_id_mbed_htm'
```

**Comment by juhhov** [comment]
```
LOG.warning(
     'Marking device with mount point "%s" as unmounted due to the '
     "following error: %s",
     device["mount_point"],
     e,
)
```
Above log row can not be found so seems that mbed.htm file can not be found from the directory.
