### ISSUE TITLE
How to run the automated tests

### ISSUE THREAD

**Issue by jsiverskog** [mbedmicro/pyOCD#759]
I'm trying to run the automated tests on an nRF 52 board using LPC-Link 2 as adapter.

I can connect and flash the board successfully using `pyocd commander --target nrf52`, but how can I specify target and binaries when running the automated tests? I get this:
```
> python test/automated_test.py
Generic 'cortex_m' target type is selected; is this intentional? You will be able to debug but not program flash. To set the target type use the '--target' argument or 'target_override' option. Use 'pyocd list --targets' to see available targets types.
==============================================
TESTING BOARD generic [cortex_m] [JXBUBZEV] #0
==============================================

Skipping board JXBUBZEV due to missing test binary
```
I have also tried to run just the basic test:
```
> python test/basic_test.py  -f file.hex
INFO:pyocd.board.board:Target type is cortex_m
WARNING:pyocd.board.board:Generic 'cortex_m' target type is selected; is this intentional? You will be able to debug but not program flash. To set the target type use the '--target' argument or 'target_override' option. Use 'pyocd list --targets' to see available targets types.
INFO:pyocd.coresight.dap:DP IDR = 0x2ba01477 (v1 rev2)
INFO:pyocd.coresight.ap:AP#0 IDR = 0x24770011 (AHB-AP var1 rev2)
INFO:pyocd.coresight.ap:AP#1 IDR = 0x02880000 (proprietary)
INFO:pyocd.coresight.rom_table:AP#0 ROM table #0 @ 0xe00ff000 (designer=244 part=008)
INFO:pyocd.coresight.rom_table:[0]<e000e000:SCS-M4 class=14 designer=43b part=00c>
INFO:pyocd.coresight.rom_table:[1]<e0001000:DWT class=14 designer=43b part=002>
INFO:pyocd.coresight.rom_table:[2]<e0002000:FPB class=14 designer=43b part=003>
INFO:pyocd.coresight.rom_table:[3]<e0000000:ITM class=14 designer=43b part=001>
INFO:pyocd.coresight.rom_table:[4]<e0040000:TPIU-M4 class=9 designer=43b part=9a1 devtype=11 archid=0000 devid=0:0:ca1>
INFO:pyocd.coresight.rom_table:[5]<e0041000:ETM-M4 class=9 designer=43b part=925 devtype=13 archid=0000 devid=0:0:0>
INFO:pyocd.coresight.cortex_m:CPU core #0 is Cortex-M4 r0p1
INFO:pyocd.coresight.cortex_m:FPU present: FPv4-SP
INFO:pyocd.coresight.dwt:4 hardware watchpoints
INFO:pyocd.coresight.fpb:6 hardware breakpoints, 4 literal comparators
binary file: file.hex
Traceback (most recent call last):
  File "test/basic_test.py", line 265, in <module>
    basic_test(None, file)
  File "test/basic_test.py", line 59, in basic_test
    addr = ram_region.start
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by flit** [comment]
You need to create a `pyocd.yaml` config file in the `test/` directory. Set the `target_override` and `test_binary` options for your probe. See the [configuration docs](https://github.com/mbedmicro/pyOCD/blob/master/docs/configuration.md) for more details.

Example copied from my own test config:
```yaml
probes:
  53FF6C066765505137602567:
    target_override: stm32f429xi
    test_binary: nucleo_f429zi.bin
  000000004420312043574641313035203730303897969903:
    target_override: nrf52840
    test_binary: l1_nrf52840-dk.bin
  ERAZAQLQ:
    target_override: lpc55s69
    test_binary: lpcxpresso55s69.bin
```
