### ISSUE TITLE
OSError: exception: access violation writing 0x00000014

### ISSUE THREAD

**Issue by maclobdell** [mbedmicro/pyOCD#776]
I get this exception consistently, but id doesn't seem to affect that actually functionality. 

Platform: CY8CKIT_062_WIFI_BT
pyOCD version: 0.23.0a2.dev28
python version: 3.7 32 bit
OS: Windows 10

Per the Readme, I've tried downloading and placing libusb v1.0.21 files (.dll, .lib, & .pdb) alongside python.exe, but this doesn't seem to help.

```
C:\Users\maclob01\OneDrive - ARM\Partners\cypress\psoc64_secure\moshe_script\psoc64_prov_tools>pyocd commander
Exception ignored in: <function _AutoFinalizedObjectBase.__del__ at 0x046CDED0>
Traceback (most recent call last):
  File "C:\Users\maclob01\AppData\Roaming\Python\Python37\site-packages\usb\_objfinalizer.py", line 84, in __del__
    self.finalize()
  File "C:\Users\maclob01\AppData\Roaming\Python\Python37\site-packages\usb\_objfinalizer.py", line 144, in finalize
    self._finalizer()
  File "c:\program files (x86)\python37-32\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\maclob01\AppData\Roaming\Python\Python37\site-packages\usb\_objfinalizer.py", line 104, in _do_finalize_object_ref
    obj._do_finalize_object()
  File "C:\Users\maclob01\AppData\Roaming\Python\Python37\site-packages\usb\_objfinalizer.py", line 71, in _do_finalize_object
    self._finalize_object()
  File "C:\Users\maclob01\AppData\Roaming\Python\Python37\site-packages\usb\backend\libusb1.py", line 604, in _finalize_object
    _lib.libusb_unref_device(self.devid)
OSError: exception: access violation writing 0x00000014
Connected to CY8C6xx7 [Sleeping]: 19001301f3091a0401f3091a00000000000000002e127069
```

**Comment by flit** [comment]
That's caused by a bug in pyusb: pyusb/pyusb#203. There's a fix merged (pyusb/pyusb#227) but it hasn't been released yet.

The reason libusb 1.0.21 was recommended is that it was thought that a change in libusb was not handled correctly in pyusb. But as you've discovered, that may not be the case.
