### ISSUE TITLE
pyOCD lpc55s69 "savemem" fails for size larger than 0x28000 using 

### ISSUE THREAD

**Issue by korjaa** [mbedmicro/pyOCD#804]
Example succeeds
```
pyocd commander -t lpc55s69 -c "savemem 0x00000000 0x00028000 dump.bin"
Saved 163840 bytes to dump.bin
```

Example fails
```
$ pyocd_launch commander -t lpc55s69 -c "savemem 0x00000000 0x00028001 dumppa.bin"
Error: transfer failed
Traceback (most recent call last):
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/cmsis_dap_probe.py", line 294, in read_ap_result_callback
    return result()
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 810, in read_reg_cb
    res = transfer.get_result()
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 141, in get_result
    self.daplink.flush()
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 665, in flush
    self._read_packet()
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 894, in _read_packet
    decoded_data = cmd.decode_data(raw_data)
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 449, in decode_data
    data = self._decode_transfer_data(data)
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 356, in _decode_transfer_data
    self._check_response(data[2])
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 335, in _check_response
    raise DAPAccessIntf.TransferFaultError()
pyocd.probe.pydapaccess.dap_access_api.DAPAccessIntf.TransferFaultError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jaakor01/workspace/pyOCD/pyocd/tools/pyocd.py", line 709, in run
    result = self.command_list[cmd](args)
  File "/home/jaakor01/workspace/pyOCD/pyocd/tools/pyocd.py", line 991, in handle_savemem
    data = bytearray(self.target.aps[self.selected_ap].read_memory_block8(addr, count))
  File "/home/jaakor01/workspace/pyOCD/pyocd/core/memory_interface.py", line 102, in read_memory_block8
    mem = self.read8(addr)
  File "/home/jaakor01/workspace/pyOCD/pyocd/core/memory_interface.py", line 64, in read8
    return self.read_memory(addr, 8, now)
  File "/home/jaakor01/workspace/pyOCD/pyocd/coresight/ap.py", line 142, in _locking
    return func(self, *args, **kwargs)
  File "/home/jaakor01/workspace/pyOCD/pyocd/coresight/ap.py", line 583, in _read_memory
    result = read_mem_cb()
  File "/home/jaakor01/workspace/pyOCD/pyocd/coresight/ap.py", line 565, in read_mem_cb
    res = result_cb()
  File "/home/jaakor01/workspace/pyOCD/pyocd/coresight/dap.py", line 412, in read_ap_cb
    result = result_cb()
  File "/home/jaakor01/workspace/pyOCD/pyocd/probe/cmsis_dap_probe.py", line 297, in read_ap_result_callback
    six.raise_from(self._convert_exception(error), error)
  File "<string>", line 3, in raise_from
pyocd.core.exceptions.TransferFaultError: SWD/JTAG Transfer Fault @ 0x00028000-0x00028000
```

Note: Using default onboard debug probe, not updated to DAPLINK.

**Comment by flit** [comment]
This is most likely related to how the LPC55S69 will fault any reads of flash sectors that have been erased but not programmed. (For "security".) Any erased-but-unprogrammed sector within the requested address range will cause a fault and premature termination of the savemem

Please try programming data to the entire address range, then rerun the savemem. .
