### ISSUE TITLE
Resource busy

### ISSUE THREAD

**Issue by blastur** [mbedmicro/pyOCD#9]
When running pyOCD using the pyUSB backend (as root) on Arch Linux I get the a usb.core.USBError: [Errno 16] Resource busy error during startup.

... which seems to indicate that the HID device is already claimed by something else. However, the is_kernel_driver_active() carried out in pyusb backend in getAllConnectedInterface() reports that no kernel driver is active. 

Manually trying to claim the interface immediately after it has been found results in the same error.

I am pretty sure there are no other applications trying to access the device. Running OpenOCD v0.8 against the same CMSIS-DAP interface works correctly.

If pyOCD is run once (failing with Resource busy error), subsequent invokations of opencd will fail until I power-cycle my mbed-device.

Traceback (most recent call last):
  File "gdbserver.py", line 26, in <module>
    board_selected = MbedBoard.chooseBoard()
  File "/usr/lib/python2.7/site-packages/pyOCD/board/mbed_board.py", line 113, in chooseBoard
    all_mbeds = MbedBoard.getAllConnectedBoards(transport, False, blocking)
  File "/usr/lib/python2.7/site-packages/pyOCD/board/mbed_board.py", line 85, in getAllConnectedBoards
    mbed.write([0x80])
  File "/usr/lib/python2.7/site-packages/pyOCD/interface/pyusb_backend.py", line 129, in write
    self.ep_out.write(data)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 283, in write
    return self.device.write(self, data, timeout)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 650, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 154, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 110, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 741, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 554, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

**Comment by c1728p9** [comment]
Has anyone seen this lately?  This sounds like it might be the same issue as #112.  If is is then it has been fixed in #110 and can be closed.  Could anyone confirm / rule out this?

**Comment by c1728p9** [comment]
Closing this issue since it is likely fixed.  Please reopen if you see it again.
